### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [gcaracuel/bureau.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by gcaracuel** [comment]
Glad to be able to. Need to rename this repo and add some edits. It was originally a fork (from a existing theme with same name) on which I put some extras.
Will rename this project and prepare the readme as soon as possible.

Thanks!

**Comment by unixorn** [comment]
Cool, either close this issue when you're done or make a PR adding the theme to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins).

**Comment by gcaracuel** [comment]
Just uploaded new readme with configuration tips and some example screenshots. I will open a pull request at https://github.com/unixorn/awesome-zsh-plugins

**Comment by unixorn** [comment]
Sounds good, thanks!
